name: ceiba_book
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  searchable_listview: ^1.3.1
  hive: ^2.0.6
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
